services:
  api:
    build: .
    ports: ["8080:8080"]
    environment:
      JWT_SECRET: "devsecret"
      EXTERNAL_API_KEY: "${EXTERNAL_API_KEY}"
      DATA_DIR: "/data"
    volumes:
      - ./data:/data
