version: "3.9"

services:
  app:
    image: imagelab:faceblur
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imagelab
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      DATA_DIR: "/data"
    volumes:
      - ./data/data
    ports:
      - "${HOST_PORT}:${APP_PORT}"  
    restart: unless-stopped
